// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNEcz5StEYRuP4EN3rq6Im0hr5HJINTzY',
    appId: '1:474383329420:web:66d2d100cd69f13f8bf3a9',
    messagingSenderId: '474383329420',
    projectId: 'harmony-2112c',
    authDomain: 'harmony-2112c.firebaseapp.com',
    storageBucket: 'harmony-2112c.appspot.com',
    measurementId: 'G-QGKBVBJMT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqJ15eGHbWK4Au5to-cglTDMyFJSwXxR8',
    appId: '1:474383329420:android:e6e216cfcde144f98bf3a9',
    messagingSenderId: '474383329420',
    projectId: 'harmony-2112c',
    storageBucket: 'harmony-2112c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefU4zOztxnoRdBlxCLg66TZLAiqruekM',
    appId: '1:474383329420:ios:79bc7e36941a9d638bf3a9',
    messagingSenderId: '474383329420',
    projectId: 'harmony-2112c',
    storageBucket: 'harmony-2112c.appspot.com',
    iosClientId: '474383329420-q2p627lfrvdqs8qrrgsj6u4kri9bnn86.apps.googleusercontent.com',
    iosBundleId: 'org.iitm.harmonyBlog',
  );
}
